spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
#      audio:
#        synthesis:
#          options:
#            model: "cosyvoice-v1"
#            voice: longxiaobai
#      image:
#        options:
#          model: qwen-image-plus

logging:
  pattern:
    console: "%d{HH:mm:ss:SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss:SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: debug  #设置日志级别
    org.springframework.ai.retry.aut oconfigure: error