spring:
  application:
    name: spring-ai-demo
  ai:
    model:
      chat: openai
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        model: deepseek-chat
        temperature: 0.7
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
