spring:
  application:
    name: spring-ai-demo
  ai:
    model:
      chat: openai
    openai:
      api-key: sk-5dbb5db2ef4341a8a29ecf798c677861
      base-url: https://api.deepseek.com
      chat:
        model: deepseek-chat
        temperature: 0.7
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
